### ISSUE TITLE
Apagar placeholder assets que não estão em uso

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#106]
## Descrição

Temos uns assets que não serão usados no website, por isso não precisam de estar presentes no repositório nem alojados no nosso website. Eis alguns exemplos:
- `src/assets/team/pessoa2a.png`
- `src/assets/team/pessoa3.png`
- `src/assets/events/previous _images` (pasta)
- `src/assets/home/missao4.jpeg`
- `src/assets/home/missao4.heic`

## Critérios de Aceitação

- [ ] Apagar assets que não estão e não serão usados no futuro

**Comment by juliamendesc** [comment]
Opa, posso pegar essa? :)

**Comment by isabelcosta** [comment]
Fiz te assign @juliamendesc ! Vou dar uma olhadela na tua PR 😉

**Comment by juliamendesc** [comment]
@isabelcosta tá à vontade para pedir alterações. Eu não sei se percebi tudo a 100%, por isso comecei desta task :)

**Comment by isabelcosta** [comment]
@juliamendesc Testei a tua PR ta tudo bem :)
Tudo que apagaste era desnecessário 👍🏾
