### ISSUE TITLE
Página 404 Not found não está a funcionar

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#108]
## Descrição

Quando tento aceder a uma página que não existe, vejo pagina em branco. Devia ver o site com header e footer, e mensagem de página não encontrada. 

Exemplo: https://raparigasdocodigo.pt/communitysdfsd

Vejo isto também a acontecer quando corro o projeto localmente.

## Como reproduzir

Passos para reproduzir o comportamento:
1. Vai para https://raparigasdocodigo.pt
2. Modifica o URL para uma página que não existe, ex: https://raparigasdocodigo.pt/asdf
3. Vê página sem conteúdo

## Comportamento Esperado

Deviamos ver uma página com o header e footer, com imagem e mensagem de 404 Not Found costumizada. Isto foi implementado antes aqui https://github.com/As-Raparigas-do-Codigo/ardc-website/pull/55.

![página 404 que já existia antes](https://user-images.githubusercontent.com/11148726/200137563-ea69a5ac-62a6-4271-ae82-97ad69f07016.png)

## Comportamento Atual

A página que não existe, simplesmente mostra página em branco.

![página em branco quando se tenta aceder a uma página que não existe](https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/11148726/d23d6756-7086-439c-ac30-16f6c5a6f5e6)

## Contexto

Recentemente houve modificações para fazer o deploy do site
### Desktop:
 - Sistema operativo: Any
 - Browser: Chrome

**Comment by saraiovieira** [comment]
Olá! Posso resolver este issue?

**Comment by isabelcosta** [comment]
Olá @saraiovieira ! Sim claro, vou atribuir a tarefa a ti 😉
