### ISSUE TITLE
Remove constantes de imagens e as imagens não usadas nos Workshops

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#109]
## Descrição

No inicio do ficheiro `src/data/activities/workshops.js`, temos umas definicoes de imagens que nao estao a ser usadas.
Por isso podemos remover estas linhas comentadas, e as imagens referidas se existirem.

## Critérios de Aceitação

- [ ] Remover linhas comentadas `//` do ficheiro `src/data/activities/workshops.js
- [ ] Remover as imagens comentadas do repositório, se não estiverem a ser usadas em mais nenhuma part do projeto

**Comment by tmanso9** [comment]
Posso tratar deste issue por favor? Posso começar a resolvê-lo amanhã.

**Comment by isabelcosta** [comment]
@tmanso9 sim claro! Vou dar te assign 😄
