### ISSUE TITLE
Automatizar a execução do linter

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#115]
## Description

This command will run the `prettier` command to format our code style in a standard way: `npm run format`
This will create a bunch of changes to fix our code style.

We should automate the linter, so that new contributions come with the appropriate code standard format.

## Acceptance Criteria

- [ ] Automate executing linter
- [ ] Add this lint format command to the README

**Comment by toothlesspanda** [comment]
We could do this in a git commit hook too

**Comment by isabelcosta** [comment]
Yes @toothlesspanda should we create another task for this?
This could be about adding the check and building this action, and the other to help prevent by using the hooks. That is the idea right?

**Comment by juliamendesc** [comment]
Hi, I'm interested in this one. Just a couple of things to ask:
- Would you be ok with husky as a tool for the hook?
- The issue title references linting, but its description references formatting. Both are different scripts, so I just want to know if you just want one of them (then which one), or if it should be both (lint then prettier).

**Comment by toothlesspanda** [comment]
> Hi, I'm interested in this one. Just a couple of things to ask:
> 
> * Would you be ok with husky as a tool for the hook?
> * The issue title references linting, but its description references formatting. Both are different scripts, so I just want to know if you just want one of them (then which one), or if it should be both (lint then prettier).

Hi!
Husky sounds like a good idea!
It can be both of them, I would say if we add this to the commits we don't need to add it to the pipeline because it will happen always before pushing code to the origin

**Comment by juliamendesc** [comment]
Alright! So if you're ok with it, I'll do this task 😊

**Comment by juliamendesc** [comment]
@isabelcosta pode fazer assign dessa pra mim também? Só pra ficar no meu record :)

**Comment by isabelcosta** [comment]
Done @juliamendesc , também mudei o titulo para refletir de forma menos especifica, o que fizeste :) GitHub action nao foi a solução, mas resolveste o problema proposto :) 💯
