### ISSUE TITLE
Conteúdo duplicado na página de Parceiros

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#116]
## Descrição

Na página de parceiros temos conteúdo duplicado.
https://raparigasdocodigo.pt/partners

## Mocks

Atualmente está assim:
![image](https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/11148726/f09dd8bf-1d07-4e51-b989-92d6b7dcc154)

## Critérios de Aceitação

- [ ] Remover conteúdo duplicado na pagina de Parceiros

**Comment by miriamspsantos** [comment]
Provavelmente um copy-paste mal sucedido! Will fix this, podes fazer assign para mim @isabelcosta :)

**Comment by isabelcosta** [comment]
Assigned!
