### ISSUE TITLE
Criar teste para verificar se a página Not Found está a ser renderizada

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#118]
## Descrição

Queremos começar a ter alguns testezitos para o site. Acho que podiamos começar com um simples teste para testar se a pagina Not Found está a renderizar os elementos desejados.

Seria bom ter um teste para conseguir detetar se a página deixar de funcionar. Um fix para esta pagina está a ser trabalho aqui https://github.com/As-Raparigas-do-Codigo/ardc-website/issues/108

Este seria o primeiro teste no projeto, por isso pode haver algum trabalho envolvido para conseguirmos correr os testes no projeto.

Links:
- https://testing-library.com/docs/react-testing-library/setup
- https://legacy.reactjs.org/docs/testing.html

## Critérios de Aceitação

- [ ] Adicionar dependencias necessarias, para conseguirmos correr testes por exemplo `npm test`
- [ ] Criar um teste simples que verifique que a página NotFound está a funcionar

**Comment by juliamendesc** [comment]
Tô com esse pronto, posso mandar? :)

**Comment by isabelcosta** [comment]
Fiz assign @juliamendesc ! Obrigada pelo interesse. Acho que vai ser uma boa task para informar os futuros contribuidores de como podem criar testes aqui no repositório :)
