### ISSUE TITLE
Resolver as sugestões do commando `npm audit`

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#119]
## Descrição

Ao correr o comando `npm audit` são sugeridas algumas alterações às dependências do projeto, devido a exporem o projeto a vulnerabilidades de segurança.
Podemos ter que atualizar alguns packages do projeto, para versões que já não exponham as vulnerabilidades.

## Critérios de Aceitação

- [ ] O commando `npm audit` não terá sugestões adicionais.

**Comment by juliamendesc** [comment]
Olha, vou pegar esta também se não tiver problema :)

**Comment by isabelcosta** [comment]
Força nisso @juliamendesc
