### ISSUE TITLE
Atualização da Página Parceiros -- Participação no Digital with Purpose

### ISSUE THREAD

**Issue by miriamspsantos** [As-Raparigas-do-Codigo/ardc-website#121]
## Descrição
Atualização das atividades que constam na página de parceiras com a nossa participação na 2ª Edição do [Digital with Purpose](https://digitalwithpurpose.org/) Global Summit 2023. 

As fotografias do evento estão [aqui](https://www.flickr.com/photos/199276062@N08/albums). 

## Critérios de Aceitação
- [ ] Adicionar um novo card com a participação no Digital with Purpose
- [ ] Associar à tag "media"
- [ ] Utilizar uma das fotografias disponibilizadas, onde apareçam as raparigas do código
- [ ] No "Vê mais aqui", linkar à página do [Digital with Purpose](https://digitalwithpurpose.org/)

**Comment by ghost** [comment]
Hi, could you assign me to do it? @miriamspsantos

**Comment by catarina-pinto** [comment]
@miriamspsantos, consegues atribuir-me este issue?

**Comment by miriamspsantos** [comment]
@catarina-pinto assigned! :)
