### ISSUE TITLE
Adicionar menção no Diretório Global das TIC à página de parceiros

### ISSUE THREAD

**Issue by miriamspsantos** [As-Raparigas-do-Codigo/ardc-website#123]
## Descrição
Adicionar a menção do Projeto As Raparigas do Código no Diretório Global das TIC

## Critérios de Aceitação
- [ ] Adicionar o card com "Raparigas do Código no Diretório Global das TIC" (ajustar conforme espaço)
- [ ] Adicionar uma fotografia (pode ser um print screen da página da revista)
- [ ] "Vê mais aqui" deve direccionar à [esta página](https://comunicacoes.apdc.pt/diretorio-global-das-tic-global-ict-directory-2022-2023/68477896/22)
- [ ] Tags devem ser "media" e "artigo"

**Comment by toothlesspanda** [comment]
Está em falta
- sub-titulo
- descrição
