### ISSUE TITLE
Adicionar framework de unit-tests

### ISSUE THREAD

**Issue by toothlesspanda** [As-Raparigas-do-Codigo/ardc-website#125]
### Description
Atualmente não existem testes nenhuns no website, seria bom introduzir unit-tests. 

### Technical Note
Para fazer isto, podemos usar o [jest](https://jestjs.io/) ou uma outra, no entanto toma liberdade em investigar e perceber qual poderá ser uma teste framework que valha a pena colocar.  (i.e. https://blog.logrocket.com/compare-react-testing-libraries/)
Tendo esta decisão, menciona neste issue qual será a ferramenta usada.

### Next steps
Os unit-tests serão feitos [aqui](https://github.com/As-Raparigas-do-Codigo/ardc-website/issues/126)

### Acceptance Criteria
- decide which framework to use presenting pros and cons of the existing frameworks ( doesn't need to be an exhausting list) and share here in the issue
- implement framework in the project

**Comment by isabelcosta** [comment]
Acho que isto ta feito com #142 cc @toothlesspanda - vou fechar ticket
Se nao for o caso podes abrir de novo 🙇🏾‍♀️
