### ISSUE TITLE
Tradução do README.md para PT

### ISSUE THREAD

**Issue by miriamspsantos** [As-Raparigas-do-Codigo/ardc-website#132]
Uma vez que as regras de contribuição e código de conduta estão em PT, deveríamos traduzir também o README.md.

**Comment by margmelo** [comment]
Hello, gostava de resolver este issue. Penso que o conseguirei fazer num dia.

Questão: Querem que mantenha a versão EN e em baixo adicione PT ou que remova EN por completo? Ou PT em cima e EN em baixo?

Obrigada :)

**Comment by isabelcosta** [comment]
Issue interessante eu tive dificuldade em traduzir o README 😅 

@margmelo vou atribuir a issue para ti. A minha opinião é ter em PT o README, mas ter um componente colapsavel, como no guia de contribuição, com a versão em inglês lá dentro. Mas pode haver outras opiniões, acho que podes criar a PR e depois os mentores podem rever.

A parte highlighted é collapsable:

<img width="1298" alt="Screenshot 2023-10-19 at 22 16 18" src="https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/11148726/2119b726-a393-4df1-bfda-a9c9fe495d97">

**Comment by margmelo** [comment]
Obrigada pelo input @isabelcosta vou pôr mãos à obra!!
