### ISSUE TITLE
Adicionar validação de email no formulário de Contactos

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#140]
## Descrição

No formulario de contacto a comunidade, o email não é validado. É possivel meter um email inválido.

## Como reproduzir

Passos para reproduzir o comportamento:
1. Vai para https://raparigasdocodigo.pt/contacts
2. Preenche o formulário, com email invalido (exemplo: sem `@`)
3. Clica em "Enviar mensagem"
4. Vê caixa de envio com sucesso

## Comportamento Esperado

Devemos ter uma mensagem de erro ao tentar submeter ou o botao deve continuar desativado. Deixo isto a escolha do/a contribuidor/a e os reviewers.

## Comportamento Atual

Vemos a mensagem de envio com sucesso 

<img width="1259" alt="image" src="https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/11148726/2e4ad522-3ded-4be0-991b-733c95387564">

## Mais informação

Pequena issue relacionada com #111

**Comment by beatriz-sabino** [comment]
Quero trabalhar nesta issue
