### ISSUE TITLE
Não consigo correr o projeto localmente

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#143]
### Problema

Não estou a conseguir correr o projeto.

No projeto limpo (acabado de clonar localmente) o que fiz para correr foi:
```
npm install
npm start
```

Acho que está relacionado com PR recente para automatizar a execução do linter https://github.com/As-Raparigas-do-Codigo/ardc-website/pull/128

❓ **Será que me falta algum passo?** 
- Algo que possamos melhorar no README, para que um novo contribuidor consiga correr o projeto sem erros?
- Existe algum requisito adicional para correr o projeto para além dos comandos que corri?

### Ambiente de desenvolvimento

```
> npm --version   
7.7.5
> node --version   
v14.4.0
```

### Erros que estou a ter

<img width="806" alt="image" src="https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/11148726/48d458f2-bb1a-45ac-87c9-050bdf778c60">

<img width="852" alt="image" src="https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/11148726/20d33b26-979f-4b6b-b1f5-78217322903a">

**Comment by juliamendesc** [comment]
Oie! Fui cuscar os requisitos do eslint e talvez seja problema de compatibilidade com as versões do seu node/npm. 

https://www.npmjs.com/package/eslint

Prerequisites: Node.js (^12.22.0, ^14.17.0, or >=16.0.0) built with SSL support. (If you are using an official Node.js distribution, SSL is always built in.)

**Comment by isabelcosta** [comment]
Ah interessante! Qual a versão que sugerias eu instalar, ou usar @juliamendesc ?

**Comment by juliamendesc** [comment]
Então, pra já é especulação né 😂.

O meu ambiente tá com o node 18. O npm acho que atualiza junto com o node, mas no npm to na latest version. No node sigo na 18 pq a 20 acho que estabilizou "recentemente". Eu uso sempre a LTS.

Você pode adicionar a 18 e colocar ela como um alias ou como default do seu ambiente, caso não trabalhe com js normalmente.

Se conseguir, me avisa que tô curiosa também 🙈

**Comment by isabelcosta** [comment]
Oi @juliamendesc foi mesmo isso! Muito Obrigada!
Atualizei o node no meu ambiente, e está a funcionar agora.

Versão antiga:
```
> node --version   
v14.4.0
```

Passos que fiz para resolver (caso alguém veja isto mais tarde):

1. Instalar pacote `n` e instalar a versão mais recente de `node`
```
npm install -g n
n latest
```

2. Verificar versão
```
> node --version
v21.1.0
```

3. Corri projeto como já o fazia e funcionou 🥳 
```
npm install
npm start
```


Acho que também poderia usar o nvm para gerir diferentes versões mas como não mexo muito com node, fiz o que foi mais simples 😅

**Comment by isabelcosta** [comment]
@toothlesspanda @gustavocr19-developer qual é a versão que aconselhariam corrermos o projeto. Não tou muito por dentro do ecosistema nodejs, e como ver a versão minima para correr o projeto. Talvez pelo menos 18, visto o que a @juliamendesc está a usar 🤔 

Pergunto porque acho que deviamos ter uma menção no README de qual é uma versão minima para poder correr o projeto, sem stress.

**Comment by gustavorodrigues19** [comment]
@isabelcosta acho que seria legal colocarmos um arquivo .nvmrc no projeto, pra não passar novamente pelo mesmo problema!
Desta forma,  a versão do node já é automaticamente detectada assim que abrir o projeto. 

O requisito pra isso funcionar automaticamente é ter o NVM configurado. 
Aqui tem um tutorial -> https://github.com/nvm-sh/nvm#automatically-call-nvm-use

**Comment by gustavorodrigues19** [comment]
Por agora, acho melhor utilizar a que está a funcionar mesmo. 
Atualizando a versão do node teríamos que alterar mais coisas... seria legal fazer isso em outra task 🙂

**Comment by isabelcosta** [comment]
Ah bom @gustavocr19-developer ! Escrevemos ao mesmo tempo 😅 
Parece me bem, pelo menos com esse ficheiro, conseguimos ter anotado algures o requisito da versão do node neh.

> Atualizando a versão do node teríamos que alterar mais coisas.

Seria v 18? neh?

**Comment by gustavorodrigues19** [comment]
Ok, pode ser a 18 sim 🙂

**Comment by isabelcosta** [comment]
Obrigada pelo feedback @gustavocr19-developer ! Vou fechar esta issue então 🙏🏾 
Vou criar a issue para criar o ficheiro que mencionaste com versao 18 :)
