### ISSUE TITLE
Fix typo na página About

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#158]
## Descrição

Typo na página "Sobre o projeto" https://raparigasdocodigo.pt/about

Reported by @danielasmp ❤️ 

## Mocks

<img src="https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/11148726/366ff818-d7df-470c-96cc-53fafbe54a35" width="300">

## Critérios de Aceitação

- [ ] Corrigir typo na página

**Comment by catarina-pinto** [comment]
@isabelcosta consegues atribuir-me este issue por favor?

**Comment by isabelcosta** [comment]
Já está! Força nisso @catarina-pinto !
