### ISSUE TITLE
Adicionar Hacktoberfest 2023 no website

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#160]
### Título da atividade

Hacktoberfest 2023

### Categoria da atividade

Evento

### Link

https://hacktoberfest.com/

### Data (DD/MM/AAAA)

01/10/2023

### Link para uma ou várias imagens do evento

https://drive.google.com/file/d/1lwCbHha50NegVyO7haYSmzeZNRh6IuA3/view?usp=drive_link

**Comment by catarina-pinto** [comment]
@isabelcosta consegues atribuir-me este issue por favor?

**Comment by isabelcosta** [comment]
Já está do teu lado 😉 @catarina-pinto
