### ISSUE TITLE
🤔 Como reduzir tamanho de imagens dos eventos

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#161]
## Descrição

Algumas imagens que temos no projeto estão com high resolution, quando não é necessário, especialmente considerando onde aparecem no site. Para algumas imagens, o facto de estarem no seu estado original significa que são grandes em tamanho (e.g.: a imagem da atividade PWD tem 15MB) que causam aquele efeito da imagem ser renderizada aos poucos na página e também consome mais _network bandwidth_ (e.g.: dados móveis mais gastos para quem estiver a fazer load do site no telele).

O último deploy (manual) mostra que o tamanho total dos ficheiros do website são 115.96 MiB. Apesar de isto não ser grande problema, se isto for reduzido, também podemos ligeiramente melhorar o tempo de deploy.

```
(...)
###### Total bytes: 115.96 MiB | Total Files: 113/113%
~/d/ardc-website dev >                                          3m 16s 13:26:43
```

## Critérios de Aceitação

- [x] Ver uma forma simples de reduzir o tamanho das imagens
- [x] Reduzir pelo menos 1 imagem
- [x] Criar issues para as restantes

**Comment by saraiovieira** [comment]
Uma sugestão pode ser comprimir as imagens em sites como https://tinypng.com/ ?

**Comment by isabelcosta** [comment]
Isso parece me bem 🤓 Não tenho muita experiência nisto, mas vi isso e achei que faz sentido.

Queres experimentar trabalhar na tarefa? 
Podes tentar com uma imagem e ver a diferença

**Comment by saraiovieira** [comment]
Sim, quero. Podes dar-me assign please?

**Comment by isabelcosta** [comment]
Sim força ai na tarefa @saraiovieira

**Comment by isabelcosta** [comment]
@saraiovieira já vi a tua PR, e está ótima! Podias por favor criar uma ou duas issues para replicar o processo para uma ou duas das maiores imagens que temos? Fica a teu critério com os queres definir ;)
E até podes meter lá o link da tua PR, visto que explica muito bem como testar a modificação!

**Comment by saraiovieira** [comment]
Obrigada :) Sim vou criar mais issues
