### ISSUE TITLE
Fix layout na página Privacy Policy

### ISSUE THREAD

**Issue by beatriz-sabino** [As-Raparigas-do-Codigo/ardc-website#163]
## Descrição

Página "Política de Privacidade" tem a informação cortada em mobile https://raparigasdocodigo.pt/privacy
## Mocks

![image](https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/85364299/e947d0eb-a7d3-4816-88d1-9f17e4f124e2)

## Critérios de Aceitação

- [ ] Corrigir layout da página em mobile

**Comment by catarina-pinto** [comment]
Conseguem atribuir-me este issue por favor? @isabelcosta @beatriz-sabino

**Comment by isabelcosta** [comment]
Já atribui a tarefa, força nisso! @catarina-pinto
