### ISSUE TITLE
Reduzir o tamanho da imagem da atividade DWP

### ISSUE THREAD

**Issue by saraiovieira** [As-Raparigas-do-Codigo/ardc-website#170]
## Descrição

A imagem da atividade PWD (Digital with Purpose Global Summit) é grande em tamanho (15MB), o que faz com que consuma mais network bandwidth e diminui a velocidade de carregamento do site. 
![Captura de ecrã 2023-11-28 173447](https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/74243584/cd17ccdc-2356-4bae-83a8-bd4d82fe1c17)

Relacionado com https://github.com/As-Raparigas-do-Codigo/ardc-website/issues/161

## Possível solução

Uma solução seria comprimir a imagem para que fique menor em tamanho de ficheiro tal como foi feito neste PR #168 para a imagem da atividade Torneiro de Padel.

**Comment by catarina-pinto** [comment]
Conseguem atribuir-me este issue por favor?

**Comment by saraiovieira** [comment]
@catarina-pinto desculpa, estava a trabalhar no PR e só vi o teu comentário agora. 
Entretanto, criei um novo issue #173 que é para fazer a mesma coisa mas para uma imagem diferente. Podes pedir para que te seja atribuído este novo issue :)

**Comment by saraiovieira** [comment]
@catarina-pinto desculpa só vi o teu comentário agora. Criei um novo issue #173 que é para fazer a mesma coisa mas para uma imagem diferente. Podes pedir para que te seja atribuído este novo issue

**Comment by isabelcosta** [comment]
Sem stress :) Obrigada @saraiovieira por criares outra para a @catarina-pinto nos ajudar a melhorar as imagens do site 🙏🏾 

Já te atribui a outra issue @catarina-pinto!
