### ISSUE TITLE
Adicionar Hacktoberfest 2022 ao website

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#171]
### Título da atividade

Hacktoberfest 2022

### Categoria da atividade

Evento

### Link

https://hacktoberfest.com/

### Data (DD/MM/AAAA)

01/10/2022

### Link para uma ou várias imagens do evento

https://drive.google.com/file/d/1Vj6WybzpizVaI-x3Q4rvBGtWRCpA9OEw/view

**Comment by catarina-pinto** [comment]
@isabelcosta consegues atribuir-me este issue por favor?
