### ISSUE TITLE
Reduzir o tamanho da imagem Directório Global das TIC

### ISSUE THREAD

**Issue by saraiovieira** [As-Raparigas-do-Codigo/ardc-website#173]
## Descrição

A imagem da atividade "Menção no Directório Global das TIC" é grande em tamanho (4.4MB), o que faz com que consuma mais network bandwidth e diminui a velocidade de carregamento do site. 

![Captura de ecrã 2023-11-30 152614](https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/74243584/73e996b3-1878-4c36-9764-6817f6ace540)

Relacionado com #161 

### Possível Solução

Uma solução seria comprimir a imagem para que fique menor em tamanho de ficheiro tal como foi feito neste PR #168 para a imagem da atividade Torneiro de Padel.

**Comment by catarina-pinto** [comment]
@saraiovieira consegues atribuir-me este issue por favor?

**Comment by isabelcosta** [comment]
@catarina-pinto Já te atribui :)
