### ISSUE TITLE
Reduzir o tamanho da imagem da atividade "Entrevista à Revista Comunicações"

### ISSUE THREAD

**Issue by saraiovieira** [As-Raparigas-do-Codigo/ardc-website#175]
## Descrição

A imagem da atividade "Entrevista à Revista Comunicações" é grande em tamanho (3MB), o que faz com que consuma mais network bandwidth e diminui a velocidade de carregamento do site.

![Captura de ecrã 2023-12-05 173415](https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/74243584/4cce555a-58dc-49c5-8151-610a497ece9b)

Relacionado com #161 

## Possível Solução

Uma solução seria comprimir a imagem para que fique menor em tamanho de ficheiro tal como foi feito neste PR #168  para a imagem da atividade Torneiro de Padel.

**Comment by catarina-pinto** [comment]
@saraiovieira Consegues atribuir-me este issue por favor?

**Comment by isabelcosta** [comment]
@catarina-pinto vou dar te assign como tenho permissões 😉
