### ISSUE TITLE
Icon metadados está com o default de react

### ISSUE THREAD

**Issue by toothlesspanda** [As-Raparigas-do-Codigo/ardc-website#176]
## Descrição

O ícone do website por vezes surge como o default de criação de um projecto em react

## Como reproduzir

Passos para reproduzir o comportamento:

1. Copiando link
2. Colar no whatsapp e esperar que faça load

## Comportamento Esperado

O icone/imagem deveria o mesmo que aparece na tab do browser

## Capturas de ecrã

![image](https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/6379428/cd4d2754-2991-40da-aaf1-44ca5491e379)

### Desktop:

- Sistema operativo: [e.g. iOS]
- Versão [e.g. 22]

### Smartphone:

- Dispositivo: iphone 13
- Sistema operativo: ios17
- App: whatsapp

**Comment by catarina-pinto** [comment]
@toothlesspanda consegues atribuir-me este issue por favor?

**Comment by isabelcosta** [comment]
Fiz assign a ti @catarina-pinto :)
