### ISSUE TITLE
Adicionar WS Gestão de Carreira 2024 ao website

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#188]
### Título da atividade

Workshop Gestão de Carreira

### Subtítulo da atividade

3a Edição

### Categoria da atividade

Workshop

### Data (DD/MM/AAAA)

19/02/2024

### Link para uma ou várias imagens do evento

https://drive.google.com/file/d/1pFP_aj6JkZFFqnm1jk-KdrJBFdtbAuoh/view

**Comment by isabelcosta** [comment]
Exemplo de uma PR que fez o mesmo que esta issue :) https://github.com/As-Raparigas-do-Codigo/ardc-website/pull/177

**Comment by tmanso9** [comment]
Posso ficar com este pff?

**Comment by isabelcosta** [comment]
Sim, claro! Vou te atribuir a tarefa @tmanso9
