### ISSUE TITLE
Adicionar etapa extra no GitHub Action de PRs para correr testes

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#192]
## Descrição

Agora que temos o nosso primeiro teste, uma boa prática para implementarmos seria ter os testes a correr quando novas PRs são criadas. Para conseguirmos detetar regressões nas funcionalidades do website com base nos testes.

Podemos adicionar um passo extra ao GitHub Action de modo, quando um push é feito para uma Pull Request (ou também para o main), podemos correr os testes.

## Mocks

Basicamente seria mais um check aqui:

<img width="937" alt="PR CI/CD checks" src="https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/11148726/df58d663-df9f-4f28-b6ed-5d39376039cc">

## Critérios de Aceitação

- [ ] Adicionar novo passo ao CI/CD que temos para cada PR, para correr tests. Devemos ver os checks a vermelho caso testes falhem, e a verde caso passem

**Comment by tmanso9** [comment]
Posso ficar com este sff?

**Comment by isabelcosta** [comment]
Já te atribui a tarefa @tmanso9 :)
Se precisares de alguma ajuda é so dizer, aqui ou no Discord
