### ISSUE TITLE
Adicionar nova opção sobre projetos Educação

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#205]
## Descrição

Adicionar nova opção de atividade chamada "Educação" ou "Escolas" para começar a ser usada na adição de novas atividades no nosso website.

Podes adicionar esta opção aqui no código: `src/constants/index.js` 

## Critérios de Aceitação

- [ ] Adicionar no código a opção "Educação" tal com opção, media, workshop, etc 
- [ ] Adicionar nova opção ao formulário: https://github.com/As-Raparigas-do-Codigo/ardc-website/blob/dev/.github/ISSUE_TEMPLATE/add_new_activity.yaml

**Comment by msantosdevlab** [comment]
Oii @isabelcosta, posso trabalhar neste issue?

**Comment by isabelcosta** [comment]
Sim força nisso! Fiz te assign @msantosdevlab
