### ISSUE TITLE
Criar filtro na pagina de Atividades

### ISSUE THREAD

**Issue by isabelcosta** [As-Raparigas-do-Codigo/ardc-website#210]
## Descrição

Temos aproximadamente 4 tipos de atividades (e.g.: evento, media, workshop, e em breve educação).
Para mais facilmente conseguirmos identificar os diferentes tipos de atividades que fazemos.

Página de atividades: https://raparigasdocodigo.pt/activities

## Mocks

Nos designs iniciais, temos este componente de filtros que podemos usar como inspiração.

<img width="891" alt="image" src="https://github.com/As-Raparigas-do-Codigo/ardc-website/assets/11148726/f163fe3a-a00c-47ec-be7d-679897ebcdc6">

Link do figma: https://www.figma.com/design/C4gY2JQcUMTWXnNBKIG8cG/01---Website?node-id=589-65 (ver secção de workshops)

## Critérios de Aceitação

- [ ] Funcionalidade para filtrar in-place as atividades, por tipo de atividade.

**Comment by msantosdevlab** [comment]
@isabelcosta posso trabalhar neste issue?

**Comment by isabelcosta** [comment]
Podes claro @msantosdevlab :) Já atribui a tarefa a ti!
